create table "public"."offices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null,
    "name" text not null,
    "description" text,
    "parent" text,
    "email" text
);

CREATE UNIQUE INDEX offices_code_key ON public.offices USING btree (code);

CREATE UNIQUE INDEX offices_pkey ON public.offices USING btree (id);

alter table "public"."offices" enable row level security;

alter table "public"."offices" add constraint "offices_pkey" PRIMARY KEY using index "offices_pkey";

alter table "public"."offices" add constraint "offices_code_key" UNIQUE using index "offices_code_key";

alter table "public"."offices" add constraint "offices_parent_fkey" FOREIGN KEY (parent) REFERENCES offices(code) not valid;

alter table "public"."offices" validate constraint "offices_parent_fkey";

alter table "public"."users" add column "office" bigint not null;

alter table "public"."users" add constraint "users_office_fkey" FOREIGN KEY (office) REFERENCES offices(id) not valid;

alter table "public"."users" validate constraint "users_office_fkey";

